(()=>{
  if(!location.pathname.startsWith('/docs'))return;
  const d=document;
  const $=(s,r=d)=>r.querySelector(s);
  const $$=(s,r=d)=>Array.from(r.querySelectorAll(s));
  const setBi=(el,en,mi)=>{if(!el)return;el.setAttribute('data-nz-en',en);el.setAttribute('data-nz-mi',mi);};
  const sync=()=>{
    const mi=d.documentElement.lang.toLowerCase().startsWith('mi');
    $$('[data-nz-en]').forEach(el=>{const v=el.getAttribute(mi?'data-nz-mi':'data-nz-en');if(v)el.textContent=v;});
  };

  const style=d.createElement('style');
  style.textContent=`
    .nz-depth-banner{margin:23px 0 0;padding:17px 19px;border:1px solid rgba(94,232,168,.24);border-radius:13px;background:linear-gradient(135deg,rgba(94,232,168,.08),rgba(107,219,255,.05));color:#c9dbe4}.nz-depth-banner strong{display:block;color:#7cf0b8;font-size:12px;margin-bottom:5px}.nz-depth-banner span{font-size:10px;line-height:1.65}
    .nz-flow{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin:18px 0 22px}.nz-flow>div{position:relative;padding:13px;border:1px solid #dce6eb;border-radius:10px;background:#fff}.nz-flow>div:not(:last-child):after{content:'→';position:absolute;right:-8px;top:50%;transform:translate(50%,-50%);z-index:2;color:#81949e;font-weight:900}.nz-flow small,.nz-flow b{display:block}.nz-flow small{color:#11885b;font:900 7px var(--mono);letter-spacing:.08em}.nz-flow b{margin-top:5px;font-size:10px;line-height:1.4}
    .nz-atlas{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin:18px 0}.nz-atlas-card{padding:18px;border:1px solid #dce6eb;border-radius:12px;background:#fff;min-height:205px;box-shadow:0 7px 24px rgba(5,30,45,.035)}.nz-atlas-card>span{display:block;color:#11885b;font:900 8px var(--mono);letter-spacing:.08em}.nz-atlas-card h3{margin:9px 0 6px;font-size:15px}.nz-atlas-card code{display:block;color:#145e89;font:850 9px/1.55 var(--mono);word-break:break-word}.nz-atlas-card ul{padding-left:17px;margin:10px 0 0;color:#637784;font-size:9px;line-height:1.7}.nz-atlas-card li+li{margin-top:2px}
    .nz-field-table{width:100%;border-collapse:collapse;margin:18px 0}.nz-field-table th,.nz-field-table td{padding:10px 11px;border-bottom:1px solid #e4ebef;text-align:left;vertical-align:top;font-size:10px}.nz-field-table th{background:#f8fafb;color:#6a7e8b;font:850 8px var(--mono);text-transform:uppercase;letter-spacing:.06em}.nz-field-table td:first-child{white-space:nowrap;color:#145e89;font:850 9px var(--mono)}.nz-field-table td:nth-child(2){color:#334f62;font-weight:750}.nz-field-table td:nth-child(3){color:#697d89}
    .nz-split{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.nz-split-card{padding:19px;border:1px solid #dce6eb;border-radius:12px;background:#fff}.nz-split-card.dark{background:#071925;border-color:#173847;color:#fff}.nz-split-card h3{margin:4px 0 8px}.nz-split-card p{margin:0}.nz-split-card.dark p{color:#a8beca}.nz-chiprow{display:flex;gap:6px;flex-wrap:wrap;margin:13px 0}.nz-chip{display:inline-flex;padding:6px 8px;border-radius:999px;background:#eef7f3;color:#0c7651;font:850 8px var(--mono)}.nz-split-card.dark .nz-chip{background:rgba(94,232,168,.08);color:#83efbb}
    .nz-value-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:18px 0}.nz-value-grid article{padding:16px;border:1px solid #dce6eb;border-radius:11px;background:#fbfdfe}.nz-value-grid b{display:block;font-size:12px}.nz-value-grid span{display:block;margin-top:5px;color:#6b7f8b;font-size:9px;line-height:1.55}
    .nz-delivery{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:18px 0}.nz-delivery article{padding:16px;border:1px solid #dce6eb;border-radius:11px;background:#fff}.nz-delivery b{display:block;font-size:11px}.nz-delivery p{margin:5px 0 0!important;font-size:9px!important}
    @media(max-width:1100px){.nz-flow{grid-template-columns:repeat(3,1fr)}.nz-flow>div:nth-child(3):after{display:none}.nz-atlas{grid-template-columns:1fr 1fr}.nz-value-grid,.nz-delivery{grid-template-columns:1fr 1fr}}
    @media(max-width:720px){.nz-flow,.nz-atlas,.nz-split,.nz-value-grid,.nz-delivery{grid-template-columns:1fr}.nz-flow>div:after{display:none}.nz-field-table{display:block;overflow-x:auto}}
  `;
  d.head.appendChild(style);

  d.title='PropData New Zealand API Docs | National Address, Parcel, Title, Building & Statutory Property Graph';
  const meta=(sel,val)=>{const el=$(sel);if(el)el.setAttribute('content',val);};
  meta('meta[name="description"]','Deep production documentation for PropData New Zealand: authoritative address identity, primary parcels, cadastral geometry, 2.45M property titles, 2.99M title-parcel relationships, 3.27M building outlines, 3.82M building-parcel relationships, derived physical intelligence and 342,695 current/historic LINZ parcel statutory actions.');
  meta('meta[property="og:title"]','PropData New Zealand | National Property Graph API Documentation');
  meta('meta[property="og:description"]','Address → parcel → titles → buildings → statutory intelligence, with relationship semantics, coverage and provenance documented end to end.');

  const hero=$('.docs-top');
  if(hero){
    const eyebrow=$('.eyebrow',hero);setBi(eyebrow,'NEW ZEALAND · NATIONAL PROPERTY GRAPH · PRODUCTION','AOTEAROA · WHATUNGA RAWA Ā-MOTU · WHAKAPUTA');
    const h1=$('h1',hero);if(h1)h1.innerHTML='<span data-nz-en="One property." data-nz-mi="Kotahi te rawa.">One property.</span><br><em data-nz-en="The full New Zealand graph behind it." data-nz-mi="Te whatunga katoa o Aotearoa kei muri.">The full New Zealand graph behind it.</em>';
    const p=$('.docs-hero>div>p',hero);setBi(p,'Start with an authoritative address, LINZ primary parcel or coordinate and traverse the property around it: cadastral identity, geometry, title records, title↔parcel relationships, building outlines, building↔parcel relationships, derived physical context, current and historic statutory actions, coverage semantics and source provenance — already joined and production-ready.','Tīmata ki tētahi wāhitau whai mana, pānga whenua matua LINZ, taunga wāhi rānei, kātahi ka whai i te rawa huri noa: tuakiri cadastral, āhuahanga, taitara, hononga taitara↔pānga whenua, tapuwae whare, hononga whare↔pānga whenua, horopaki tinana kua tātaihia, mahi ā-ture onāianei me ngā mahi o mua, semantika kapi me te takenga puna — kua hono kē, kua rite mō te whakaputa.');
    const actions=$('.docs-actions',hero);actions?.insertAdjacentHTML('afterend','<div class="nz-depth-banner"><strong data-nz-en="The routes are the doorway. The graph is the product." data-nz-mi="Ko ngā ara te kūaha. Ko te whatunga te hua.">The routes are the doorway. The graph is the product.</strong><span data-nz-en="New Zealand deliberately uses a compact resolver surface. One successful property resolution can attach multiple national source and derived relationship domains without forcing your application to rebuild LINZ ingestion, cadastral reconciliation, title joins, spatial linking, statutory normalization or coverage logic." data-nz-mi="He mata resolver tōtika tō Aotearoa. Ka taea e tētahi whakataunga rawa angitu te hono i ngā paparanga puna ā-motu me ngā hononga kua tātaihia, me te kore e hanga anō tō taupānga i te uta LINZ, te whakatikatika cadastral, ngā hononga taitara, te hononga mokowā, te whakaraupapa ā-ture, te arorau kapi rānei.">New Zealand deliberately uses a compact resolver surface. One successful property resolution can attach multiple national source and derived relationship domains without forcing your application to rebuild LINZ ingestion, cadastral reconciliation, title joins, spatial linking, statutory normalization or coverage logic.</span></div>');
    const rows=$$('.hero-contract-row',hero);
    if(rows[1])rows[1].innerHTML='<div><span data-nz-en="National source systems" data-nz-mi="Ngā pūnaha puna ā-motu">National source systems</span><strong data-nz-en="Addresses · parcels · titles · buildings · statutory actions" data-nz-mi="Wāhitau · pānga whenua · taitara · whare · mahi ā-ture">Addresses · parcels · titles · buildings · statutory actions</strong></div><code>LINZ</code>';
    if(rows[2])rows[2].innerHTML='<div><span data-nz-en="Relationship products" data-nz-mi="Ngā hua hononga">Relationship products</span><strong data-nz-en="Title↔parcel · building↔parcel · derived physical context" data-nz-mi="Taitara↔pānga · whare↔pānga · horopaki tinana kua tātaihia">Title↔parcel · building↔parcel · derived physical context</strong></div><code>GRAPH</code>';
    if(rows[3])rows[3].innerHTML='<div><span data-nz-en="Delivery" data-nz-mi="Tukunga">Delivery</span><strong>REST · OAuth MCP · RapidAPI · bulk · white-label · custom</strong></div><code>LIVE</code>';
  }

  const overview=$('#overview');
  if(overview){
    const kicker=$('.doc-kicker',overview);setBi(kicker,'NATIONAL PROPERTY-GRAPH ARCHITECTURE','HANGA WHATUNGA RAWA Ā-MOTU');
    const h2=$('h2',overview);setBi(h2,'The endpoint resolves identity. PropData returns the system around it.','Ka whakatauria e te endpoint te tuakiri. Ka whakahokia e PropData te pūnaha huri noa.');
    const p=$('p',overview);setBi(p,'New Zealand is not a flat parcel database behind a country flag. PropData preserves the country-native property model: authoritative addresses resolve to cadastral identity; parcels carry geometry and appellation context; titles remain separate legal records connected through explicit many-to-many relationships; buildings remain separate physical objects connected through spatial relationships; statutory actions remain source-attached legal events. Coverage and provenance travel with each layer.','Ehara a Aotearoa i tētahi pātengi raraunga pānga whenua papatahi kei muri i tētahi haki whenua. Ka tiakina e PropData te tauira rawa taketake: ka whakatauria ngā wāhitau whai mana ki te tuakiri cadastral; ka mau ngā pānga whenua i te āhuahanga me te ingoa ture; ka noho ngā taitara hei rekoata ture motuhake me ngā hononga maha-ki-maha; ka noho ngā whare hei ahanoa tinana motuhake me ngā hononga mokowā; ka noho ngā mahi ā-ture hei kaupapa ture kua herea ki te puna. Ka haere tahi te kapi me te takenga me ia paparanga.');
    const map=$('.contract-map',overview);
    if(map)map.innerHTML=`
      <article class="map-card"><span>01 · RESOLVE</span><b>Address / parcel / coordinates</b><p>Start from the identifier your product actually has.</p></article>
      <article class="map-card"><span>02 · CADASTRE</span><b>Primary parcel identity</b><p>Parcel ID, appellation, land district, area, topology and available geometry.</p></article>
      <article class="map-card"><span>03 · LEGAL GRAPH</span><b>Titles + title↔parcel</b><p>Keep legal title records and their many-to-many cadastral relationships explicit.</p></article>
      <article class="map-card"><span>04 · PHYSICAL GRAPH</span><b>Buildings + building↔parcel</b><p>Keep source footprints separate from derived spatial relationships and physical summaries.</p></article>
      <article class="map-card"><span>05 · STATUTORY</span><b>Current + historic actions</b><p>Attach bounded LINZ/Landonline parcel-action intelligence without inventing vague flags.</p></article>
      <article class="map-card"><span>06 · CONTRACT</span><b>Coverage + provenance</b><p>Match, source coverage and derived-relationship provenance remain independently inspectable.</p></article>
      <article class="map-card"><span>07 · AUTOMATION</span><b>Refresh + reconciliation</b><p>National baselines and bounded changesets are maintained behind the API contract.</p></article>
      <article class="map-card"><span>08 · DELIVER</span><b>REST · MCP · bulk · embedded</b><p>Use the same country intelligence through the delivery shape your product needs.</p></article>`;
  }

  if(overview&&!$('#response-atlas'))overview.insertAdjacentHTML('afterend',`
    <section class="doc-section" id="response-atlas">
      <div class="doc-kicker" data-nz-en="RESPONSE ATLAS" data-nz-mi="MAPI WHAKAUTU">RESPONSE ATLAS</div>
      <h2 data-nz-en="What one New Zealand property resolution can actually unlock." data-nz-mi="He aha ka taea e tētahi whakataunga rawa o Aotearoa te whakatuwhera.">What one New Zealand property resolution can actually unlock.</h2>
      <p data-nz-en="Think in domains, not endpoint count. The production response can combine verified source layers and PropData relationship products around one canonical property context. Exact fields remain governed by the resolved property's coverage and account entitlement." data-nz-mi="Whakaarohia ngā paraka raraunga, kaua ko te maha o ngā endpoint. Ka taea e te whakautu whakaputa te whakakotahi i ngā paparanga puna kua whakamana me ngā hua hononga PropData huri noa i tētahi horopaki rawa kotahi. Ka whakatauria ngā āpure tika e te kapi o te rawa me ngā motika o te pūkete.">Think in domains, not endpoint count. The production response can combine verified source layers and PropData relationship products around one canonical property context. Exact fields remain governed by the resolved property's coverage and account entitlement.</p>
      <div class="nz-flow"><div><small>01 · INPUT</small><b>Address / parcel / WGS84</b></div><div><small>02 · IDENTITY</small><b>Address + primary parcel</b></div><div><small>03 · LEGAL</small><b>Titles + title↔parcel</b></div><div><small>04 · PHYSICAL</small><b>Buildings + building↔parcel</b></div><div><small>05 · STATUTORY</small><b>Current + historic actions</b></div><div><small>06 · OUTPUT</small><b>Coverage-aware property graph</b></div></div>
      <div class="nz-atlas">
        <article class="nz-atlas-card"><span>01 · ADDRESS IDENTITY</span><h3>Authoritative address context</h3><code>address · coordinates · locality / road structure · lifecycle</code><ul><li>2,424,415 national baseline</li><li>Source-native identity and coordinates</li><li>Address match stays separate from parcel resolution</li></ul></article>
        <article class="nz-atlas-card"><span>02 · PRIMARY PARCEL</span><h3>Cadastral property identity</h3><code>parcel_id · appellation · land_district · area · topology</code><ul><li>3,040,571 national baseline</li><li>New Zealand-native parcel semantics</li><li>Canonical anchor for deeper graph attachment</li></ul></article>
        <article class="nz-atlas-card"><span>03 · PARCEL GEOMETRY</span><h3>Spatial property context</h3><code>geometry · coordinate containment · spatial match</code><ul><li>Source geometry where available</li><li>Coordinate→containing-property workflow</li><li>Coverage probe before location-dependent promises</li></ul></article>
        <article class="nz-atlas-card"><span>04 · PROPERTY TITLES</span><h3>Legal title records</h3><code>title_no · status · title_type · issue_date · estate_description</code><ul><li>2,450,998 title baseline</li><li>Guarantee + owner-count metadata where published</li><li>Title identity is not collapsed into owner identity</li></ul></article>
        <article class="nz-atlas-card"><span>05 · TITLE ↔ PARCEL</span><h3>Many-to-many legal/cadastral graph</h3><code>title relationships · multi-title · unit-title · shared extents</code><ul><li>2,988,279 explicit associations</li><li>Preserves multi-title property structure</li><li>Supports unit-title/shared-spatial contexts</li></ul></article>
        <article class="nz-atlas-card"><span>06 · BUILDING OUTLINES</span><h3>Physical source objects</h3><code>footprint geometry · capture method · imagery/source provenance</code><ul><li>3,268,141 national source baseline</li><li>Capture-source names/groups and dates where published</li><li>Null source geometry remains null</li></ul></article>
        <article class="nz-atlas-card"><span>07 · BUILDING ↔ PARCEL</span><h3>Derived spatial relationship graph</h3><code>method · confidence basis · overlap area · overlap ratio · metric CRS</code><ul><li>3,820,845 relationships</li><li>Separate from source building records</li><li>Geometry-repair provenance preserved where applicable</li></ul></article>
        <article class="nz-atlas-card"><span>08 · DERIVED PHYSICAL</span><h3>Property-level building context</h3><code>building_count · primary_building_count · building_overlap_area_ratio</code><ul><li>Summaries derived from explicit spatial relationships</li><li>Coverage state distinguishes zero from unavailable</li><li>Useful for underwriting, mapping and product profiles</li></ul></article>
        <article class="nz-atlas-card"><span>09 · STATUTORY ACTIONS</span><h3>Current + historic parcel actions</h3><code>new_zealand.legal_actions</code><ul><li>342,695 normalized actions</li><li>Current / historic + create / extinguished / referenced summaries</li><li>Bounded items, source revision and coverage state</li></ul></article>
        <article class="nz-atlas-card"><span>10 · RESPONSE CONTRACT</span><h3>Production semantics</h3><code>match_level · coverage_status · parcel_resolution · count · returned · truncated</code><ul><li>Base identity and optional enrichment stay independent</li><li>Fail-open enrichment; fail-closed facts</li><li>Source / provenance travels with the result</li></ul></article>
        <article class="nz-atlas-card"><span>11 · OPERATIONS</span><h3>Country-aware control plane</h3><code>/v1/countries · /v1/auth/usage · /v1/health · /v1/stats · /v1/changelog</code><ul><li>Capabilities, quota, health and releases</li><li>Property-level coverage remains authoritative</li><li>Same global PropData account model</li></ul></article>
        <article class="nz-atlas-card"><span>12 · DELIVERY</span><h3>More than request/response REST</h3><code>REST · OAuth MCP · RapidAPI · bulk · custom · white-label · embedded</code><ul><li>Commercial delivery can match the workflow</li><li>Multi-country PropData contracts available</li><li>One governed source-aware country model</li></ul></article>
      </div>
    </section>`);

  const full=$('#full-enrich');
  if(full){
    setBi($('.doc-kicker',full),'ONE CALL · MULTIPLE PROPERTY SYSTEMS','KOTAHI TONO · HE MAHA NGĀ PŪNAHA RAWA');
    setBi($('h2',full),'Full Enrich is a graph traversal, not a bigger parcel row.','Ko Full Enrich he haerenga whatunga, ehara i te rārangi pānga whenua nui ake.');
    setBi($('p',full),'Full Enrich starts from the verified canonical property context and conditionally attaches the legal, physical, statutory and derived intelligence that coverage supports. Each layer keeps its own source and delivery state so one missing enrichment cannot erase valid property identity.','Ka tīmata a Full Enrich i te horopaki rawa kua whakamana, ā, ka hono i te mōhiotanga ture, tinana, ā-ture me te mōhiotanga kua tātaihia e tautokona ana e te kapi. Ka pupuri ia paparanga i tōna ake puna me te tūnga tuku, kia kore tētahi rikanga ngaro e muku i te tuakiri rawa tika.');
    const grid=$('.layer-grid',full);
    if(grid)grid.innerHTML=`
      <article class="layer-card"><span class="layer-no">IDENTITY</span><h3>Address + parcel</h3><p>Authoritative input resolution, canonical parcel identity, appellation, district, area and topology.</p></article>
      <article class="layer-card"><span class="layer-no">SPATIAL</span><h3>Parcel geometry</h3><p>Available source geometry and coordinate containment with explicit spatial match semantics.</p></article>
      <article class="layer-card"><span class="layer-no">LEGAL RECORDS</span><h3>Property titles</h3><p>Title status, type, issue date, guarantee status, estate description and published owner-count metadata.</p></article>
      <article class="layer-card"><span class="layer-no">LEGAL GRAPH</span><h3>Title ↔ parcel</h3><p>Explicit many-to-many relationships preserving multi-title, unit-title and shared-spatial contexts.</p></article>
      <article class="layer-card"><span class="layer-no">PHYSICAL SOURCE</span><h3>Building outlines</h3><p>National LINZ footprints with capture and imagery/source provenance where published.</p></article>
      <article class="layer-card"><span class="layer-no">PHYSICAL GRAPH</span><h3>Building ↔ parcel + derived</h3><p>Spatial relationships with overlap/provenance plus property-level building counts and overlap summaries.</p></article>
      <article class="layer-card"><span class="layer-no">LEGAL / STATUTORY</span><h3>Current + historic actions</h3><p>Certified LINZ 51565 parcel actions at <code>new_zealand.legal_actions</code> with bounded counts, items and coverage.</p></article>
      <article class="layer-card"><span class="layer-no">CONTRACT</span><h3>Coverage + provenance</h3><p>Layer-specific match, availability, counts, truncation and source context make the response safe to use in production.</p></article>`;
  }

  const graph=$('#graph');
  if(graph){
    setBi($('.doc-kicker',graph),'NATIONAL SOURCE + RELATIONSHIP INFRASTRUCTURE','HANGANGA PUNA + HONONGA Ā-MOTU');
    setBi($('h2',graph),'Seven national graph layers. Millions of explicit relationships.','E whitu ngā paparanga whatunga ā-motu. He miriona ngā hononga mārama.');
    setBi($('p',graph),'These are not seven labels for seven API endpoints. They are the national source baselines and relationship products PropData keeps reconciled behind the New Zealand property contract. Source records and derived relationships remain distinguishable so downstream software can understand what is authoritative, what is joined and how the join was produced.','Ehara ēnei i te whitu tapanga mō ngā endpoint e whitu. Koinei ngā paparanga puna ā-motu me ngā hua hononga e whakatikatikahia ana e PropData i muri i te kirimana rawa o Aotearoa. Ka noho wehe ngā rekoata puna me ngā hononga kua tātaihia kia mārama ai te pūmanawa ki te mea whai mana, te mea kua hono me te āhua o te hononga.');
  }

  const titles=$('#titles');
  if(titles&&!$('.nz-field-table',titles)){
    titles.insertAdjacentHTML('beforeend',`
      <h3 data-nz-en="Title record field map" data-nz-mi="Mahere āpure taitara">Title record field map</h3>
      <table class="nz-field-table"><thead><tr><th>Field</th><th data-nz-en="Domain" data-nz-mi="Paraka">Domain</th><th data-nz-en="What it means" data-nz-mi="Te tikanga">What it means</th></tr></thead><tbody>
        <tr><td>title_no</td><td>legal identity</td><td>Source title identifier.</td></tr><tr><td>status</td><td>title lifecycle</td><td>Published title status such as LIVE.</td></tr><tr><td>title_type</td><td>legal structure</td><td>Published title class, including Unit Title where applicable.</td></tr><tr><td>land_district</td><td>jurisdiction</td><td>LINZ land-district context attached to the title.</td></tr><tr><td>issue_date</td><td>lifecycle</td><td>Published title issue timestamp.</td></tr><tr><td>guarantee_status</td><td>title metadata</td><td>Published guarantee-status context.</td></tr><tr><td>estate_description</td><td>estate structure</td><td>Source estate description, preserving unit/stratum/freehold language.</td></tr><tr><td>number_owners</td><td>count metadata</td><td>Published owner count only; it is not named owner identity.</td></tr><tr><td>spatial_extents_shared</td><td>spatial semantics</td><td>Signals title geometry/shared-spatial context where present.</td></tr><tr><td>source</td><td>provenance</td><td>Authoritative source attribution.</td></tr>
      </tbody></table>
      <div class="nz-split"><article class="nz-split-card"><h3>Title records ≠ parcel records</h3><p>PropData preserves legal title identity as its own object instead of forcing one title onto one parcel. That matters for unit titles, multi-title properties and shared extents.</p></article><article class="nz-split-card dark"><h3>2,988,279 explicit title↔parcel edges</h3><p>The relationship graph is a first-class product layer. Applications can reason about legal/cadastral structure without reconstructing the many-to-many join themselves.</p></article></div>`);
  }

  const buildings=$('#buildings');
  if(buildings&&!$('.nz-split',buildings)){
    buildings.insertAdjacentHTML('beforeend',`
      <div class="nz-split"><article class="nz-split-card"><div class="doc-kicker">SOURCE OBJECT</div><h3>3,268,141 LINZ building outlines</h3><p>The source layer preserves footprint geometry as published and can retain capture method, capture-source name/group, source date ranges, last-modified context and LINZ provenance where those fields are published.</p><div class="nz-chiprow"><span class="nz-chip">footprint geometry</span><span class="nz-chip">capture method</span><span class="nz-chip">capture source</span><span class="nz-chip">source dates</span><span class="nz-chip">last modified</span><span class="nz-chip">LINZ provenance</span></div></article><article class="nz-split-card dark"><div class="doc-kicker">DERIVED RELATIONSHIP</div><h3>3,820,845 building↔parcel links</h3><p>PropData creates a separate spatial relationship product and preserves how it was produced rather than presenting proximity as certainty.</p><div class="nz-chiprow"><span class="nz-chip">relationship method</span><span class="nz-chip">confidence basis</span><span class="nz-chip">overlap area</span><span class="nz-chip">overlap ratio</span><span class="nz-chip">metric CRS</span><span class="nz-chip">geometry repair provenance</span></div></article></div>
      <h3 data-nz-en="Derived physical-property contract" data-nz-mi="Kirimana horopaki tinana kua tātaihia">Derived physical-property contract</h3><table class="nz-field-table"><thead><tr><th>Field / signal</th><th>Layer</th><th>Use</th></tr></thead><tbody><tr><td>coverage_status</td><td>relationship graph</td><td>Distinguishes complete linkage coverage from unavailable linkage coverage.</td></tr><tr><td>count / returned / truncated</td><td>collection</td><td>Separates total relationships from bounded response items.</td></tr><tr><td>relationship method</td><td>derived edge</td><td>Explains how the building and parcel were connected.</td></tr><tr><td>overlap area / ratio</td><td>spatial evidence</td><td>Quantifies spatial intersection rather than relying on nearest-neighbour proximity.</td></tr><tr><td>metric CRS</td><td>processing provenance</td><td>Preserves the New Zealand metric coordinate-system basis used for area/overlap calculations.</td></tr><tr><td>geometry repair provenance</td><td>processing provenance</td><td>Keeps geometry correction/repair context visible where applicable.</td></tr><tr><td>derived.building_count</td><td>property summary</td><td>Count of related building objects where relationship coverage supports it.</td></tr><tr><td>derived.primary_building_count</td><td>property summary</td><td>Primary-building summary derived from the relationship graph.</td></tr><tr><td>derived.building_overlap_area_ratio</td><td>property summary</td><td>Property-level overlap signal produced from explicit spatial relationships.</td></tr></tbody></table>`);
  }

  const statutory=$('#statutory');
  if(statutory&&!$('.nz-field-table',statutory)){
    statutory.insertAdjacentHTML('beforeend',`
      <h3 data-nz-en="Statutory response contract" data-nz-mi="Kirimana whakautu ā-ture">Statutory response contract</h3><table class="nz-field-table"><thead><tr><th>Field / metric</th><th>Meaning</th><th>Production behavior</th></tr></thead><tbody><tr><td>coverage_status</td><td>Layer availability for this parcel.</td><td>Read before interpreting a zero count.</td></tr><tr><td>count</td><td>Total normalized actions attached to the parcel.</td><td>May exceed returned items when bounded.</td></tr><tr><td>current_count</td><td>Actions classified as current.</td><td>Kept separate from historic records.</td></tr><tr><td>historic_count</td><td>Actions classified as historic.</td><td>Preserves history instead of collapsing it into a present-tense flag.</td></tr><tr><td>action_counts.create</td><td>Create-class actions.</td><td>National loaded count: 197,039.</td></tr><tr><td>action_counts.extinguished</td><td>Extinguished-class actions.</td><td>National loaded count: 33,816.</td></tr><tr><td>action_counts.referenced</td><td>Referenced-class actions.</td><td>National loaded count: 111,840.</td></tr><tr><td>returned / truncated</td><td>Bounded collection semantics.</td><td>Lets clients distinguish summary completeness from response item limits.</td></tr><tr><td>source_dataset_id</td><td>LINZ source dataset identity.</td><td>Certified layer uses dataset 51565.</td></tr><tr><td>source revision</td><td>Refresh/source context.</td><td>Supports traceability across automated changeset refreshes.</td></tr></tbody></table>
      <div class="notice blue"><strong>Why this matters:</strong> PropData does not reduce a 12-event parcel history to a generic <code>has_legal_issue=true</code> flag. The application can distinguish current from historic, understand action families, inspect bounded source-aware items, and decide what the event means for its own workflow.</div>`);
  }

  const platform=$('#platform');
  if(platform&&!$('#delivery-model'))platform.insertAdjacentHTML('afterend',`
    <section class="doc-section" id="delivery-model"><div class="doc-kicker" data-nz-en="COMMERCIAL DELIVERY" data-nz-mi="TUKUNGA ARUMONI">COMMERCIAL DELIVERY</div><h2 data-nz-en="The New Zealand graph is not limited to one-request-at-a-time REST." data-nz-mi="Kāore te whatunga o Aotearoa e herea ki te REST tono-kotahi-i-te-wā.">The New Zealand graph is not limited to one-request-at-a-time REST.</h2><p data-nz-en="The same source-aware country model can be delivered through the commercial shape the customer actually needs. Authentication and entitlement remain appropriate to each channel; direct REST keys never belong in client-side MCP flows." data-nz-mi="Ka taea te tuku i taua tauira whenua whai-puna mā te ara arumoni e hiahiatia ana e te kiritaki. Ka noho tika te whakamana me ngā motika mō ia hongere; kāore ngā kī REST tika e tika ana mō ngā rerenga MCP taha-kiritaki.">The same source-aware country model can be delivered through the commercial shape the customer actually needs. Authentication and entitlement remain appropriate to each channel; direct REST keys never belong in client-side MCP flows.</p><div class="nz-delivery"><article><b>Production REST API</b><p>Country-aware property resolution through the shared PropData edge.</p></article><article><b>OAuth MCP</b><p>AI-client workflows through the separate OAuth-protected PropData MCP authorization flow.</p></article><article><b>RapidAPI distribution</b><p>Marketplace consumption for applicable plans and developer workflows.</p></article><article><b>Bulk / data licensing</b><p>Large-scale delivery when per-request access is not the right operating model.</p></article><article><b>Custom endpoints</b><p>Workflow-specific contracts for enterprise applications.</p></article><article><b>White-label</b><p>Embed PropData-backed New Zealand intelligence into another customer experience.</p></article><article><b>Embedded infrastructure</b><p>Use the country graph as a product capability rather than a separate data project.</p></article><article><b>Multi-country PropData</b><p>Reuse the broader platform relationship across New Zealand and other supported markets.</p></article></div></section>`);

  const sources=$('#sources');
  if(sources&&!$('.nz-value-grid',sources))sources.insertAdjacentHTML('beforeend',`
    <h3 data-nz-en="What PropData adds above the source systems" data-nz-mi="He aha tā PropData e tāpiri ana ki runga ake i ngā puna">What PropData adds above the source systems</h3><div class="nz-value-grid"><article><b>National ingestion</b><span>Maintained country-scale source baselines instead of one-off file downloads.</span></article><article><b>Canonical property identity</b><span>Stable property context across address, parcel, title and physical layers.</span></article><article><b>Title relationship graph</b><span>2.99M explicit many-to-many title↔parcel associations.</span></article><article><b>Building relationship graph</b><span>3.82M spatial building↔parcel edges with method and provenance.</span></article><article><b>Metric spatial processing</b><span>New Zealand-appropriate CRS handling for overlap and area calculations.</span></article><article><b>Geometry-repair provenance</b><span>Processing context remains inspectable rather than silently rewritten.</span></article><article><b>Statutory normalization</b><span>Current/historic and action-family summaries above raw LINZ/Landonline events.</span></article><article><b>Bounded response semantics</b><span>Count, returned and truncated signals make large related collections safe to consume.</span></article><article><b>Coverage controls</b><span>Zero, unavailable and partial enrichment remain distinguishable.</span></article><article><b>Refresh automation</b><span>National baselines plus bounded/resumable changeset workflows behind production.</span></article><article><b>Provenance</b><span>Source identity stays attached to both authoritative facts and derived relationships.</span></article><article><b>Commercial delivery</b><span>REST, MCP, bulk, custom, white-label and multi-country packaging above one country graph.</span></article></div>`);

  const side=$('.docs-side');
  if(side&&!$('[href="#response-atlas"]',side)){
    const start=$('b',side);
    start?.insertAdjacentHTML('afterend','<a href="#response-atlas" data-nz-en="Full response atlas" data-nz-mi="Mapi whakautu katoa">Full response atlas</a>');
    const contractLabels=$$('b',side);const contract=contractLabels.find(x=>x.textContent?.trim()==='Contract');
    contract?.insertAdjacentHTML('beforebegin','<b data-nz-en="Delivery" data-nz-mi="Tukunga">Delivery</b><a href="#delivery-model" data-nz-en="Commercial delivery" data-nz-mi="Tukunga arumoni">Commercial delivery</a>');
  }

  // Keep added content synchronized with the existing EN / MI controls.
  $$('.lang-btn').forEach(btn=>btn.addEventListener('click',()=>setTimeout(sync,0)));
  new MutationObserver(sync).observe(d.documentElement,{attributes:true,attributeFilter:['lang']});
  sync();
})();
